language: objective-c
osx_image: xcode7

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

script:
    - set -o pipefail
    - xcodebuild -workspace TDConnectIosSdk.xcworkspace -scheme TDConnectIosSdkTests -sdk iphonesimulator -destination "OS=9.0,name=iPhone 6 Plus" -configuration Release clean test
    - xcodebuild -workspace TDConnectIosSdk.xcworkspace -scheme TDConnectIosSdkTests -sdk iphonesimulator -destination "OS=8.4,name=iPhone 6 Plus" -configuration Release clean test

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
